version: "3.9"
services:
    project:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
        env_file:
            - .env
        depends_on:
            - database
    database:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
          - "5432:5432"
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready
            interval: 5s
            timeout: 10s
            retries: 5